/* Generated by Cython 0.14 on Tue Dec 21 12:30:57 2010 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#ifndef Py_PYTHON_H
    #error Python headers needed to compile C extensions, please install development version of Python.
#else

#include <stddef.h> /* For offsetof */
#ifndef offsetof
#define offsetof(type, member) ( (size_t) & ((type*)0) -> member )
#endif

#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
  #ifndef __fastcall
    #define __fastcall
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(t) t
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif

#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif

#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
  #define PyDict_CheckExact(op) (Py_TYPE(op) == &PyDict_Type)
  #define PyDict_Contains(d,o)   PySequence_Contains(d,o)
#endif

#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PY_FORMAT_SIZE_T ""
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
  #define PyErr_WarnEx(category, message, stacklevel) PyErr_Warn(category, message)
#endif

#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   (((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,
  #define PyType_Modified(t)

  typedef struct {
     void *buf;
     PyObject *obj;
     Py_ssize_t len;
     Py_ssize_t itemsize;
     int readonly;
     int ndim;
     char *format;
     Py_ssize_t *shape;
     Py_ssize_t *strides;
     Py_ssize_t *suboffsets;
     void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

#endif

#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif

#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif

#if (PY_VERSION_HEX < 0x02060000) || (PY_MAJOR_VERSION >= 3)
  #define Py_TPFLAGS_HAVE_NEWBUFFER 0
#endif

#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyStringObject               PyUnicodeObject
  #define PyString_Type                PyUnicode_Type
  #define PyString_Check               PyUnicode_Check
  #define PyString_CheckExact          PyUnicode_CheckExact
#endif

#if PY_VERSION_HEX < 0x02060000
  #define PyBytesObject                PyStringObject
  #define PyBytes_Type                 PyString_Type
  #define PyBytes_Check                PyString_Check
  #define PyBytes_CheckExact           PyString_CheckExact
  #define PyBytes_FromString           PyString_FromString
  #define PyBytes_FromStringAndSize    PyString_FromStringAndSize
  #define PyBytes_FromFormat           PyString_FromFormat
  #define PyBytes_DecodeEscape         PyString_DecodeEscape
  #define PyBytes_AsString             PyString_AsString
  #define PyBytes_AsStringAndSize      PyString_AsStringAndSize
  #define PyBytes_Size                 PyString_Size
  #define PyBytes_AS_STRING            PyString_AS_STRING
  #define PyBytes_GET_SIZE             PyString_GET_SIZE
  #define PyBytes_Repr                 PyString_Repr
  #define PyBytes_Concat               PyString_Concat
  #define PyBytes_ConcatAndDel         PyString_ConcatAndDel
  #define PySet_Check(obj)             PyObject_TypeCheck(obj, &PySet_Type)
  #define PyFrozenSet_Check(obj)       PyObject_TypeCheck(obj, &PyFrozenSet_Type)
#endif

#ifndef PySet_CheckExact
#  define PySet_CheckExact(obj)          (Py_TYPE(obj) == &PySet_Type)
#endif

#if PY_MAJOR_VERSION >= 3
  #define PyIntObject                  PyLongObject
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
#endif

#if PY_MAJOR_VERSION >= 3
  #define PyBoolObject PyLongObject
#endif


#if PY_MAJOR_VERSION >= 3
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
  #define __Pyx_PyNumber_InPlaceDivide(x,y)  PyNumber_InPlaceTrueDivide(x,y)
#else
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_Divide(x,y)
  #define __Pyx_PyNumber_InPlaceDivide(x,y)  PyNumber_InPlaceDivide(x,y)
#endif

#if (PY_MAJOR_VERSION < 3) || (PY_VERSION_HEX >= 0x03010300)
  #define __Pyx_PySequence_GetSlice(obj, a, b) PySequence_GetSlice(obj, a, b)
  #define __Pyx_PySequence_SetSlice(obj, a, b, value) PySequence_SetSlice(obj, a, b, value)
  #define __Pyx_PySequence_DelSlice(obj, a, b) PySequence_DelSlice(obj, a, b)
#else
  #define __Pyx_PySequence_GetSlice(obj, a, b) (unlikely(!(obj)) ? \
        (PyErr_SetString(PyExc_SystemError, "null argument to internal routine"), (PyObject*)0) : \
        (likely((obj)->ob_type->tp_as_mapping) ? (PySequence_GetSlice(obj, a, b)) : \
            (PyErr_Format(PyExc_TypeError, "'%.200s' object is unsliceable", (obj)->ob_type->tp_name), (PyObject*)0)))
  #define __Pyx_PySequence_SetSlice(obj, a, b, value) (unlikely(!(obj)) ? \
        (PyErr_SetString(PyExc_SystemError, "null argument to internal routine"), -1) : \
        (likely((obj)->ob_type->tp_as_mapping) ? (PySequence_SetSlice(obj, a, b, value)) : \
            (PyErr_Format(PyExc_TypeError, "'%.200s' object doesn't support slice assignment", (obj)->ob_type->tp_name), -1)))
  #define __Pyx_PySequence_DelSlice(obj, a, b) (unlikely(!(obj)) ? \
        (PyErr_SetString(PyExc_SystemError, "null argument to internal routine"), -1) : \
        (likely((obj)->ob_type->tp_as_mapping) ? (PySequence_DelSlice(obj, a, b)) : \
            (PyErr_Format(PyExc_TypeError, "'%.200s' object doesn't support slice deletion", (obj)->ob_type->tp_name), -1)))
#endif

#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) ((self) ? PyMethod_New(func, self) : PyInstanceMethod_New(func))
#endif

#if PY_VERSION_HEX < 0x02050000
  #define __Pyx_GetAttrString(o,n)   PyObject_GetAttrString((o),((char *)(n)))
  #define __Pyx_SetAttrString(o,n,a) PyObject_SetAttrString((o),((char *)(n)),(a))
  #define __Pyx_DelAttrString(o,n)   PyObject_DelAttrString((o),((char *)(n)))
#else
  #define __Pyx_GetAttrString(o,n)   PyObject_GetAttrString((o),(n))
  #define __Pyx_SetAttrString(o,n,a) PyObject_SetAttrString((o),(n),(a))
  #define __Pyx_DelAttrString(o,n)   PyObject_DelAttrString((o),(n))
#endif

#if PY_VERSION_HEX < 0x02050000
  #define __Pyx_NAMESTR(n) ((char *)(n))
  #define __Pyx_DOCSTR(n)  ((char *)(n))
#else
  #define __Pyx_NAMESTR(n) (n)
  #define __Pyx_DOCSTR(n)  (n)
#endif

#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif

#if defined(WIN32) || defined(MS_WINDOWS)
#define _USE_MATH_DEFINES
#endif
#include <math.h>
#define __PYX_HAVE_API__order_parameter
#include "arrayobject.h"
#include "math.h"

#ifdef PYREX_WITHOUT_ASSERTIONS
#define CYTHON_WITHOUT_ASSERTIONS
#endif


/* inline attribute */
#ifndef CYTHON_INLINE
  #if defined(__GNUC__)
    #define CYTHON_INLINE __inline__
  #elif defined(_MSC_VER)
    #define CYTHON_INLINE __inline
  #elif defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
    #define CYTHON_INLINE inline
  #else
    #define CYTHON_INLINE
  #endif
#endif

/* unused attribute */
#ifndef CYTHON_UNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define CYTHON_UNUSED __attribute__ ((__unused__))
#   else
#     define CYTHON_UNUSED
#   endif
# elif defined(__ICC) || defined(__INTEL_COMPILER)
#   define CYTHON_UNUSED __attribute__ ((__unused__))
# else
#   define CYTHON_UNUSED
# endif
#endif

typedef struct {PyObject **p; char *s; const long n; const char* encoding; const char is_unicode; const char is_str; const char intern; } __Pyx_StringTabEntry; /*proto*/


/* Type Conversion Predeclarations */

#define __Pyx_PyBytes_FromUString(s) PyBytes_FromString((char*)s)
#define __Pyx_PyBytes_AsUString(s)   ((unsigned char*) PyBytes_AsString(s))

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static CYTHON_INLINE int __Pyx_PyObject_IsTrue(PyObject*);
static CYTHON_INLINE PyObject* __Pyx_PyNumber_Int(PyObject* x);

static CYTHON_INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject*);
static CYTHON_INLINE PyObject * __Pyx_PyInt_FromSize_t(size_t);
static CYTHON_INLINE size_t __Pyx_PyInt_AsSize_t(PyObject*);

#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))


#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 || (__GNUC__ == 2 && (__GNUC_MINOR__ > 95))
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static PyObject *__pyx_empty_bytes;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;


static const char *__pyx_f[] = {
  "order_parameter.pyx",
  "numeric.pxi",
};

/* Type declarations */

#ifndef CYTHON_REFNANNY
  #define CYTHON_REFNANNY 0
#endif

#if CYTHON_REFNANNY
  typedef struct {
    void (*INCREF)(void*, PyObject*, int);
    void (*DECREF)(void*, PyObject*, int);
    void (*GOTREF)(void*, PyObject*, int);
    void (*GIVEREF)(void*, PyObject*, int);
    void* (*SetupContext)(const char*, int, const char*);
    void (*FinishContext)(void**);
  } __Pyx_RefNannyAPIStruct;
  static __Pyx_RefNannyAPIStruct *__Pyx_RefNanny = NULL;
  static __Pyx_RefNannyAPIStruct * __Pyx_RefNannyImportAPI(const char *modname) {
    PyObject *m = NULL, *p = NULL;
    void *r = NULL;
    m = PyImport_ImportModule((char *)modname);
    if (!m) goto end;
    p = PyObject_GetAttrString(m, (char *)"RefNannyAPI");
    if (!p) goto end;
    r = PyLong_AsVoidPtr(p);
  end:
    Py_XDECREF(p);
    Py_XDECREF(m);
    return (__Pyx_RefNannyAPIStruct *)r;
  }
  #define __Pyx_RefNannySetupContext(name)           void *__pyx_refnanny = __Pyx_RefNanny->SetupContext((name), __LINE__, __FILE__)
  #define __Pyx_RefNannyFinishContext()           __Pyx_RefNanny->FinishContext(&__pyx_refnanny)
  #define __Pyx_INCREF(r) __Pyx_RefNanny->INCREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_DECREF(r) __Pyx_RefNanny->DECREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_GOTREF(r) __Pyx_RefNanny->GOTREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_GIVEREF(r) __Pyx_RefNanny->GIVEREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_XDECREF(r) do { if((r) != NULL) {__Pyx_DECREF(r);} } while(0)
#else
  #define __Pyx_RefNannySetupContext(name)
  #define __Pyx_RefNannyFinishContext()
  #define __Pyx_INCREF(r) Py_INCREF(r)
  #define __Pyx_DECREF(r) Py_DECREF(r)
  #define __Pyx_GOTREF(r)
  #define __Pyx_GIVEREF(r)
  #define __Pyx_XDECREF(r) Py_XDECREF(r)
#endif /* CYTHON_REFNANNY */
#define __Pyx_XGIVEREF(r) do { if((r) != NULL) {__Pyx_GIVEREF(r);} } while(0)
#define __Pyx_XGOTREF(r) do { if((r) != NULL) {__Pyx_GOTREF(r);} } while(0)

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name, PyObject* kw_name); /*proto*/

static void __Pyx_RaiseArgtupleInvalid(const char* func_name, int exact,
    Py_ssize_t num_min, Py_ssize_t num_max, Py_ssize_t num_found); /*proto*/

static int __Pyx_ParseOptionalKeywords(PyObject *kwds, PyObject **argnames[],     PyObject *kwds2, PyObject *values[], Py_ssize_t num_pos_args,     const char* function_name); /*proto*/

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed,
    const char *name, int exact); /*proto*/

static CYTHON_INLINE unsigned char __Pyx_PyInt_AsUnsignedChar(PyObject *);

static CYTHON_INLINE unsigned short __Pyx_PyInt_AsUnsignedShort(PyObject *);

static CYTHON_INLINE unsigned int __Pyx_PyInt_AsUnsignedInt(PyObject *);

static CYTHON_INLINE char __Pyx_PyInt_AsChar(PyObject *);

static CYTHON_INLINE short __Pyx_PyInt_AsShort(PyObject *);

static CYTHON_INLINE int __Pyx_PyInt_AsInt(PyObject *);

static CYTHON_INLINE signed char __Pyx_PyInt_AsSignedChar(PyObject *);

static CYTHON_INLINE signed short __Pyx_PyInt_AsSignedShort(PyObject *);

static CYTHON_INLINE signed int __Pyx_PyInt_AsSignedInt(PyObject *);

static CYTHON_INLINE int __Pyx_PyInt_AsLongDouble(PyObject *);

static CYTHON_INLINE unsigned long __Pyx_PyInt_AsUnsignedLong(PyObject *);

static CYTHON_INLINE unsigned PY_LONG_LONG __Pyx_PyInt_AsUnsignedLongLong(PyObject *);

static CYTHON_INLINE long __Pyx_PyInt_AsLong(PyObject *);

static CYTHON_INLINE PY_LONG_LONG __Pyx_PyInt_AsLongLong(PyObject *);

static CYTHON_INLINE signed long __Pyx_PyInt_AsSignedLong(PyObject *);

static CYTHON_INLINE signed PY_LONG_LONG __Pyx_PyInt_AsSignedLongLong(PyObject *);

static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name, long size, int strict);  /*proto*/

static PyObject *__Pyx_ImportModule(const char *name); /*proto*/

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
/* Module declarations from Scientific.N */

/* Module declarations from order_parameter */

static PyTypeObject *__pyx_ptype_15order_parameter_array_type = 0;
static CYTHON_INLINE double __pyx_f_15order_parameter_round(double); /*proto*/
#define __Pyx_MODULE_NAME "order_parameter"
int __pyx_module_is_main_order_parameter = 0;

/* Implementation of order_parameter */
static char __pyx_k__nd[] = "nd";
static char __pyx_k__data[] = "data";
static char __pyx_k__descr[] = "descr";
static char __pyx_k__elsize[] = "elsize";
static char __pyx_k__hIndex[] = "hIndex";
static char __pyx_k__oIndex[] = "oIndex";
static char __pyx_k__scalec[] = "scalec";
static char __pyx_k__scaleh[] = "scaleh";
static char __pyx_k__scaleo[] = "scaleo";
static char __pyx_k__indexes[] = "indexes";
static char __pyx_k____main__[] = "__main__";
static char __pyx_k____test__[] = "__test__";
static char __pyx_k__type_num[] = "type_num";
static char __pyx_k__dimensions[] = "dimensions";
static char __pyx_k__directCell[] = "directCell";
static char __pyx_k__reverseCell[] = "reverseCell";
static char __pyx_k__configuration[] = "configuration";
static char __pyx_k__order_parameter[] = "order_parameter";
static char __pyx_k__conversionFactor[] = "conversionFactor";
static PyObject *__pyx_n_s____main__;
static PyObject *__pyx_n_s____test__;
static PyObject *__pyx_n_s__configuration;
static PyObject *__pyx_n_s__conversionFactor;
static PyObject *__pyx_n_s__data;
static PyObject *__pyx_n_s__descr;
static PyObject *__pyx_n_s__dimensions;
static PyObject *__pyx_n_s__directCell;
static PyObject *__pyx_n_s__elsize;
static PyObject *__pyx_n_s__hIndex;
static PyObject *__pyx_n_s__indexes;
static PyObject *__pyx_n_s__nd;
static PyObject *__pyx_n_s__oIndex;
static PyObject *__pyx_n_s__order_parameter;
static PyObject *__pyx_n_s__reverseCell;
static PyObject *__pyx_n_s__scalec;
static PyObject *__pyx_n_s__scaleh;
static PyObject *__pyx_n_s__scaleo;
static PyObject *__pyx_n_s__type_num;

/* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":12
 *     double tanh(double x)
 * 
 * cdef inline double round(double r):             # <<<<<<<<<<<<<<
 *     return floor(r + 0.5) if (r > 0.0) else ceil(r - 0.5)
 * 
 */

static CYTHON_INLINE double __pyx_f_15order_parameter_round(double __pyx_v_r) {
  double __pyx_r;
  double __pyx_t_1;
  __Pyx_RefNannySetupContext("round");

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":13
 * 
 * cdef inline double round(double r):
 *     return floor(r + 0.5) if (r > 0.0) else ceil(r - 0.5)             # <<<<<<<<<<<<<<
 * 
 * def order_parameter(array_type configuration, int hIndex, int oIndex, array_type directCell, array_type reverseCell,\
 */
  if ((__pyx_v_r > 0.0)) {
    __pyx_t_1 = floor((__pyx_v_r + 0.5));
  } else {
    __pyx_t_1 = ceil((__pyx_v_r - 0.5));
  }
  __pyx_r = __pyx_t_1;
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":15
 *     return floor(r + 0.5) if (r > 0.0) else ceil(r - 0.5)
 * 
 * def order_parameter(array_type configuration, int hIndex, int oIndex, array_type directCell, array_type reverseCell,\             # <<<<<<<<<<<<<<
 *                     array_type indexes, array_type scalec, array_type scaleh, array_type scaleo, double conversionFactor):
 * 
 */

static PyObject *__pyx_pf_15order_parameter_0order_parameter(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_15order_parameter_0order_parameter = {__Pyx_NAMESTR("order_parameter"), (PyCFunction)__pyx_pf_15order_parameter_0order_parameter, METH_VARARGS|METH_KEYWORDS, __Pyx_DOCSTR(0)};
static PyObject *__pyx_pf_15order_parameter_0order_parameter(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyArrayObject *__pyx_v_configuration = 0;
  int __pyx_v_hIndex;
  int __pyx_v_oIndex;
  PyArrayObject *__pyx_v_directCell = 0;
  PyArrayObject *__pyx_v_reverseCell = 0;
  PyArrayObject *__pyx_v_indexes = 0;
  PyArrayObject *__pyx_v_scalec = 0;
  PyArrayObject *__pyx_v_scaleh = 0;
  PyArrayObject *__pyx_v_scaleo = 0;
  double __pyx_v_conversionFactor;
  int *__pyx_v_atomindex;
  double *__pyx_v_config;
  double *__pyx_v_cell;
  double *__pyx_v_rcell;
  double *__pyx_v_scaleconfig;
  double *__pyx_v_scalehposition;
  double *__pyx_v_scaleoposition;
  double __pyx_v_x;
  double __pyx_v_y;
  double __pyx_v_z;
  double __pyx_v_sdx;
  double __pyx_v_sdy;
  double __pyx_v_sdz;
  double __pyx_v_rx;
  double __pyx_v_ry;
  double __pyx_v_rz;
  double __pyx_v_r;
  double __pyx_v_s2;
  int __pyx_v_i;
  int __pyx_v_ind;
  PyObject *__pyx_r = NULL;
  int __pyx_t_1;
  int __pyx_t_2;
  int __pyx_t_3;
  int __pyx_t_4;
  PyObject *__pyx_t_5 = NULL;
  static PyObject **__pyx_pyargnames[] = {&__pyx_n_s__configuration,&__pyx_n_s__hIndex,&__pyx_n_s__oIndex,&__pyx_n_s__directCell,&__pyx_n_s__reverseCell,&__pyx_n_s__indexes,&__pyx_n_s__scalec,&__pyx_n_s__scaleh,&__pyx_n_s__scaleo,&__pyx_n_s__conversionFactor,0};
  __Pyx_RefNannySetupContext("order_parameter");
  __pyx_self = __pyx_self;
  if (unlikely(__pyx_kwds)) {
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    PyObject* values[10] = {0,0,0,0,0,0,0,0,0,0};
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case 10: values[9] = PyTuple_GET_ITEM(__pyx_args, 9);
      case  9: values[8] = PyTuple_GET_ITEM(__pyx_args, 8);
      case  8: values[7] = PyTuple_GET_ITEM(__pyx_args, 7);
      case  7: values[6] = PyTuple_GET_ITEM(__pyx_args, 6);
      case  6: values[5] = PyTuple_GET_ITEM(__pyx_args, 5);
      case  5: values[4] = PyTuple_GET_ITEM(__pyx_args, 4);
      case  4: values[3] = PyTuple_GET_ITEM(__pyx_args, 3);
      case  3: values[2] = PyTuple_GET_ITEM(__pyx_args, 2);
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_n_s__configuration);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
      case  1:
      values[1] = PyDict_GetItem(__pyx_kwds, __pyx_n_s__hIndex);
      if (likely(values[1])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("order_parameter", 1, 10, 10, 1); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  2:
      values[2] = PyDict_GetItem(__pyx_kwds, __pyx_n_s__oIndex);
      if (likely(values[2])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("order_parameter", 1, 10, 10, 2); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  3:
      values[3] = PyDict_GetItem(__pyx_kwds, __pyx_n_s__directCell);
      if (likely(values[3])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("order_parameter", 1, 10, 10, 3); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  4:
      values[4] = PyDict_GetItem(__pyx_kwds, __pyx_n_s__reverseCell);
      if (likely(values[4])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("order_parameter", 1, 10, 10, 4); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  5:
      values[5] = PyDict_GetItem(__pyx_kwds, __pyx_n_s__indexes);
      if (likely(values[5])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("order_parameter", 1, 10, 10, 5); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  6:
      values[6] = PyDict_GetItem(__pyx_kwds, __pyx_n_s__scalec);
      if (likely(values[6])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("order_parameter", 1, 10, 10, 6); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  7:
      values[7] = PyDict_GetItem(__pyx_kwds, __pyx_n_s__scaleh);
      if (likely(values[7])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("order_parameter", 1, 10, 10, 7); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  8:
      values[8] = PyDict_GetItem(__pyx_kwds, __pyx_n_s__scaleo);
      if (likely(values[8])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("order_parameter", 1, 10, 10, 8); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  9:
      values[9] = PyDict_GetItem(__pyx_kwds, __pyx_n_s__conversionFactor);
      if (likely(values[9])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("order_parameter", 1, 10, 10, 9); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "order_parameter") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_configuration = ((PyArrayObject *)values[0]);
    __pyx_v_hIndex = __Pyx_PyInt_AsInt(values[1]); if (unlikely((__pyx_v_hIndex == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    __pyx_v_oIndex = __Pyx_PyInt_AsInt(values[2]); if (unlikely((__pyx_v_oIndex == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    __pyx_v_directCell = ((PyArrayObject *)values[3]);
    __pyx_v_reverseCell = ((PyArrayObject *)values[4]);
    __pyx_v_indexes = ((PyArrayObject *)values[5]);
    __pyx_v_scalec = ((PyArrayObject *)values[6]);
    __pyx_v_scaleh = ((PyArrayObject *)values[7]);
    __pyx_v_scaleo = ((PyArrayObject *)values[8]);
    __pyx_v_conversionFactor = __pyx_PyFloat_AsDouble(values[9]); if (unlikely((__pyx_v_conversionFactor == (double)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  } else if (PyTuple_GET_SIZE(__pyx_args) != 10) {
    goto __pyx_L5_argtuple_error;
  } else {
    __pyx_v_configuration = ((PyArrayObject *)PyTuple_GET_ITEM(__pyx_args, 0));
    __pyx_v_hIndex = __Pyx_PyInt_AsInt(PyTuple_GET_ITEM(__pyx_args, 1)); if (unlikely((__pyx_v_hIndex == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    __pyx_v_oIndex = __Pyx_PyInt_AsInt(PyTuple_GET_ITEM(__pyx_args, 2)); if (unlikely((__pyx_v_oIndex == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    __pyx_v_directCell = ((PyArrayObject *)PyTuple_GET_ITEM(__pyx_args, 3));
    __pyx_v_reverseCell = ((PyArrayObject *)PyTuple_GET_ITEM(__pyx_args, 4));
    __pyx_v_indexes = ((PyArrayObject *)PyTuple_GET_ITEM(__pyx_args, 5));
    __pyx_v_scalec = ((PyArrayObject *)PyTuple_GET_ITEM(__pyx_args, 6));
    __pyx_v_scaleh = ((PyArrayObject *)PyTuple_GET_ITEM(__pyx_args, 7));
    __pyx_v_scaleo = ((PyArrayObject *)PyTuple_GET_ITEM(__pyx_args, 8));
    __pyx_v_conversionFactor = __pyx_PyFloat_AsDouble(PyTuple_GET_ITEM(__pyx_args, 9)); if (unlikely((__pyx_v_conversionFactor == (double)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("order_parameter", 1, 10, 10, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("order_parameter.order_parameter");
  __Pyx_RefNannyFinishContext();
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_configuration), __pyx_ptype_15order_parameter_array_type, 1, "configuration", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_directCell), __pyx_ptype_15order_parameter_array_type, 1, "directCell", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_reverseCell), __pyx_ptype_15order_parameter_array_type, 1, "reverseCell", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_indexes), __pyx_ptype_15order_parameter_array_type, 1, "indexes", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_scalec), __pyx_ptype_15order_parameter_array_type, 1, "scalec", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_scaleh), __pyx_ptype_15order_parameter_array_type, 1, "scaleh", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_scaleo), __pyx_ptype_15order_parameter_array_type, 1, "scaleo", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":26
 * 
 *     # Checks the dimension of the input arrays.
 *     assert configuration.nd == 2             # <<<<<<<<<<<<<<
 *     assert directCell.nd == 1
 *     assert reverseCell.nd == 1
 */
  #ifndef CYTHON_WITHOUT_ASSERTIONS
  if (unlikely(!(__pyx_v_configuration->nd == 2))) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  #endif

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":27
 *     # Checks the dimension of the input arrays.
 *     assert configuration.nd == 2
 *     assert directCell.nd == 1             # <<<<<<<<<<<<<<
 *     assert reverseCell.nd == 1
 *     assert indexes.nd == 1
 */
  #ifndef CYTHON_WITHOUT_ASSERTIONS
  if (unlikely(!(__pyx_v_directCell->nd == 1))) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  #endif

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":28
 *     assert configuration.nd == 2
 *     assert directCell.nd == 1
 *     assert reverseCell.nd == 1             # <<<<<<<<<<<<<<
 *     assert indexes.nd == 1
 *     assert scalec.nd == 1
 */
  #ifndef CYTHON_WITHOUT_ASSERTIONS
  if (unlikely(!(__pyx_v_reverseCell->nd == 1))) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  #endif

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":29
 *     assert directCell.nd == 1
 *     assert reverseCell.nd == 1
 *     assert indexes.nd == 1             # <<<<<<<<<<<<<<
 *     assert scalec.nd == 1
 *     assert scaleh.nd == 1
 */
  #ifndef CYTHON_WITHOUT_ASSERTIONS
  if (unlikely(!(__pyx_v_indexes->nd == 1))) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  #endif

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":30
 *     assert reverseCell.nd == 1
 *     assert indexes.nd == 1
 *     assert scalec.nd == 1             # <<<<<<<<<<<<<<
 *     assert scaleh.nd == 1
 *     assert scaleo.nd == 1
 */
  #ifndef CYTHON_WITHOUT_ASSERTIONS
  if (unlikely(!(__pyx_v_scalec->nd == 1))) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  #endif

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":31
 *     assert indexes.nd == 1
 *     assert scalec.nd == 1
 *     assert scaleh.nd == 1             # <<<<<<<<<<<<<<
 *     assert scaleo.nd == 1
 * 
 */
  #ifndef CYTHON_WITHOUT_ASSERTIONS
  if (unlikely(!(__pyx_v_scaleh->nd == 1))) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  #endif

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":32
 *     assert scalec.nd == 1
 *     assert scaleh.nd == 1
 *     assert scaleo.nd == 1             # <<<<<<<<<<<<<<
 * 
 *     # Checks the types of the input arrays.
 */
  #ifndef CYTHON_WITHOUT_ASSERTIONS
  if (unlikely(!(__pyx_v_scaleo->nd == 1))) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  #endif

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":35
 * 
 *     # Checks the types of the input arrays.
 *     assert configuration.descr.type_num  == PyArray_DOUBLE             # <<<<<<<<<<<<<<
 *     assert directCell.descr.type_num     == PyArray_DOUBLE
 *     assert reverseCell.descr.type_num    == PyArray_DOUBLE
 */
  #ifndef CYTHON_WITHOUT_ASSERTIONS
  if (unlikely(!(__pyx_v_configuration->descr->type_num == PyArray_DOUBLE))) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  #endif

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":36
 *     # Checks the types of the input arrays.
 *     assert configuration.descr.type_num  == PyArray_DOUBLE
 *     assert directCell.descr.type_num     == PyArray_DOUBLE             # <<<<<<<<<<<<<<
 *     assert reverseCell.descr.type_num    == PyArray_DOUBLE
 *     assert scalec.descr.type_num         == PyArray_DOUBLE
 */
  #ifndef CYTHON_WITHOUT_ASSERTIONS
  if (unlikely(!(__pyx_v_directCell->descr->type_num == PyArray_DOUBLE))) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  #endif

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":37
 *     assert configuration.descr.type_num  == PyArray_DOUBLE
 *     assert directCell.descr.type_num     == PyArray_DOUBLE
 *     assert reverseCell.descr.type_num    == PyArray_DOUBLE             # <<<<<<<<<<<<<<
 *     assert scalec.descr.type_num         == PyArray_DOUBLE
 *     assert scaleh.descr.type_num         == PyArray_DOUBLE
 */
  #ifndef CYTHON_WITHOUT_ASSERTIONS
  if (unlikely(!(__pyx_v_reverseCell->descr->type_num == PyArray_DOUBLE))) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  #endif

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":38
 *     assert directCell.descr.type_num     == PyArray_DOUBLE
 *     assert reverseCell.descr.type_num    == PyArray_DOUBLE
 *     assert scalec.descr.type_num         == PyArray_DOUBLE             # <<<<<<<<<<<<<<
 *     assert scaleh.descr.type_num         == PyArray_DOUBLE
 *     assert scaleo.descr.type_num         == PyArray_DOUBLE
 */
  #ifndef CYTHON_WITHOUT_ASSERTIONS
  if (unlikely(!(__pyx_v_scalec->descr->type_num == PyArray_DOUBLE))) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  #endif

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":39
 *     assert reverseCell.descr.type_num    == PyArray_DOUBLE
 *     assert scalec.descr.type_num         == PyArray_DOUBLE
 *     assert scaleh.descr.type_num         == PyArray_DOUBLE             # <<<<<<<<<<<<<<
 *     assert scaleo.descr.type_num         == PyArray_DOUBLE
 * 
 */
  #ifndef CYTHON_WITHOUT_ASSERTIONS
  if (unlikely(!(__pyx_v_scaleh->descr->type_num == PyArray_DOUBLE))) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  #endif

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":40
 *     assert scalec.descr.type_num         == PyArray_DOUBLE
 *     assert scaleh.descr.type_num         == PyArray_DOUBLE
 *     assert scaleo.descr.type_num         == PyArray_DOUBLE             # <<<<<<<<<<<<<<
 * 
 *     assert (indexes.descr.type_num == PyArray_INT or indexes.descr.type_num == PyArray_LONG) \
 */
  #ifndef CYTHON_WITHOUT_ASSERTIONS
  if (unlikely(!(__pyx_v_scaleo->descr->type_num == PyArray_DOUBLE))) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  #endif

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":42
 *     assert scaleo.descr.type_num         == PyArray_DOUBLE
 * 
 *     assert (indexes.descr.type_num == PyArray_INT or indexes.descr.type_num == PyArray_LONG) \             # <<<<<<<<<<<<<<
 *     and indexes.descr.elsize == sizeof(int)
 * 
 */
  #ifndef CYTHON_WITHOUT_ASSERTIONS

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":43
 * 
 *     assert (indexes.descr.type_num == PyArray_INT or indexes.descr.type_num == PyArray_LONG) \
 *     and indexes.descr.elsize == sizeof(int)             # <<<<<<<<<<<<<<
 * 
 *     config = <double *>configuration.data
 */
  __pyx_t_1 = (__pyx_v_indexes->descr->type_num == PyArray_INT);
  if (!__pyx_t_1) {

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":42
 *     assert scaleo.descr.type_num         == PyArray_DOUBLE
 * 
 *     assert (indexes.descr.type_num == PyArray_INT or indexes.descr.type_num == PyArray_LONG) \             # <<<<<<<<<<<<<<
 *     and indexes.descr.elsize == sizeof(int)
 * 
 */
    __pyx_t_2 = (__pyx_v_indexes->descr->type_num == PyArray_LONG);
    __pyx_t_3 = __pyx_t_2;
  } else {
    __pyx_t_3 = __pyx_t_1;
  }
  if (__pyx_t_3) {

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":43
 * 
 *     assert (indexes.descr.type_num == PyArray_INT or indexes.descr.type_num == PyArray_LONG) \
 *     and indexes.descr.elsize == sizeof(int)             # <<<<<<<<<<<<<<
 * 
 *     config = <double *>configuration.data
 */
    __pyx_t_1 = (__pyx_v_indexes->descr->elsize == (sizeof(int)));
    __pyx_t_2 = __pyx_t_1;
  } else {
    __pyx_t_2 = __pyx_t_3;
  }
  if (unlikely(!__pyx_t_2)) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  #endif

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":45
 *     and indexes.descr.elsize == sizeof(int)
 * 
 *     config = <double *>configuration.data             # <<<<<<<<<<<<<<
 *     cell = <double *>directCell.data
 *     rcell = <double *>reverseCell.data
 */
  __pyx_v_config = ((double *)__pyx_v_configuration->data);

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":46
 * 
 *     config = <double *>configuration.data
 *     cell = <double *>directCell.data             # <<<<<<<<<<<<<<
 *     rcell = <double *>reverseCell.data
 *     atomindex = <int *>indexes.data
 */
  __pyx_v_cell = ((double *)__pyx_v_directCell->data);

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":47
 *     config = <double *>configuration.data
 *     cell = <double *>directCell.data
 *     rcell = <double *>reverseCell.data             # <<<<<<<<<<<<<<
 *     atomindex = <int *>indexes.data
 *     scaleconfig = <double *> scalec.data
 */
  __pyx_v_rcell = ((double *)__pyx_v_reverseCell->data);

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":48
 *     cell = <double *>directCell.data
 *     rcell = <double *>reverseCell.data
 *     atomindex = <int *>indexes.data             # <<<<<<<<<<<<<<
 *     scaleconfig = <double *> scalec.data
 *     scalehposition = <double *> scaleh.data
 */
  __pyx_v_atomindex = ((int *)__pyx_v_indexes->data);

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":49
 *     rcell = <double *>reverseCell.data
 *     atomindex = <int *>indexes.data
 *     scaleconfig = <double *> scalec.data             # <<<<<<<<<<<<<<
 *     scalehposition = <double *> scaleh.data
 *     scaleoposition = <double *> scaleo.data
 */
  __pyx_v_scaleconfig = ((double *)__pyx_v_scalec->data);

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":50
 *     atomindex = <int *>indexes.data
 *     scaleconfig = <double *> scalec.data
 *     scalehposition = <double *> scaleh.data             # <<<<<<<<<<<<<<
 *     scaleoposition = <double *> scaleo.data
 * 
 */
  __pyx_v_scalehposition = ((double *)__pyx_v_scaleh->data);

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":51
 *     scaleconfig = <double *> scalec.data
 *     scalehposition = <double *> scaleh.data
 *     scaleoposition = <double *> scaleo.data             # <<<<<<<<<<<<<<
 * 
 *     scalehposition[0] = config[3*hIndex]*rcell[0] + config[3*hIndex+1]*rcell[3] + config[3*hIndex+2]*rcell[6]
 */
  __pyx_v_scaleoposition = ((double *)__pyx_v_scaleo->data);

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":53
 *     scaleoposition = <double *> scaleo.data
 * 
 *     scalehposition[0] = config[3*hIndex]*rcell[0] + config[3*hIndex+1]*rcell[3] + config[3*hIndex+2]*rcell[6]             # <<<<<<<<<<<<<<
 *     scalehposition[1] = config[3*hIndex]*rcell[1] + config[3*hIndex+1]*rcell[4] + config[3*hIndex+2]*rcell[7]
 *     scalehposition[2] = config[3*hIndex]*rcell[2] + config[3*hIndex+1]*rcell[5] + config[3*hIndex+2]*rcell[8]
 */
  (__pyx_v_scalehposition[0]) = ((((__pyx_v_config[(3 * __pyx_v_hIndex)]) * (__pyx_v_rcell[0])) + ((__pyx_v_config[((3 * __pyx_v_hIndex) + 1)]) * (__pyx_v_rcell[3]))) + ((__pyx_v_config[((3 * __pyx_v_hIndex) + 2)]) * (__pyx_v_rcell[6])));

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":54
 * 
 *     scalehposition[0] = config[3*hIndex]*rcell[0] + config[3*hIndex+1]*rcell[3] + config[3*hIndex+2]*rcell[6]
 *     scalehposition[1] = config[3*hIndex]*rcell[1] + config[3*hIndex+1]*rcell[4] + config[3*hIndex+2]*rcell[7]             # <<<<<<<<<<<<<<
 *     scalehposition[2] = config[3*hIndex]*rcell[2] + config[3*hIndex+1]*rcell[5] + config[3*hIndex+2]*rcell[8]
 * 
 */
  (__pyx_v_scalehposition[1]) = ((((__pyx_v_config[(3 * __pyx_v_hIndex)]) * (__pyx_v_rcell[1])) + ((__pyx_v_config[((3 * __pyx_v_hIndex) + 1)]) * (__pyx_v_rcell[4]))) + ((__pyx_v_config[((3 * __pyx_v_hIndex) + 2)]) * (__pyx_v_rcell[7])));

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":55
 *     scalehposition[0] = config[3*hIndex]*rcell[0] + config[3*hIndex+1]*rcell[3] + config[3*hIndex+2]*rcell[6]
 *     scalehposition[1] = config[3*hIndex]*rcell[1] + config[3*hIndex+1]*rcell[4] + config[3*hIndex+2]*rcell[7]
 *     scalehposition[2] = config[3*hIndex]*rcell[2] + config[3*hIndex+1]*rcell[5] + config[3*hIndex+2]*rcell[8]             # <<<<<<<<<<<<<<
 * 
 *     scaleoposition[0] = config[3*oIndex]*rcell[0] + config[3*oIndex+1]*rcell[3] + config[3*oIndex+2]*rcell[6]
 */
  (__pyx_v_scalehposition[2]) = ((((__pyx_v_config[(3 * __pyx_v_hIndex)]) * (__pyx_v_rcell[2])) + ((__pyx_v_config[((3 * __pyx_v_hIndex) + 1)]) * (__pyx_v_rcell[5]))) + ((__pyx_v_config[((3 * __pyx_v_hIndex) + 2)]) * (__pyx_v_rcell[8])));

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":57
 *     scalehposition[2] = config[3*hIndex]*rcell[2] + config[3*hIndex+1]*rcell[5] + config[3*hIndex+2]*rcell[8]
 * 
 *     scaleoposition[0] = config[3*oIndex]*rcell[0] + config[3*oIndex+1]*rcell[3] + config[3*oIndex+2]*rcell[6]             # <<<<<<<<<<<<<<
 *     scaleoposition[1] = config[3*oIndex]*rcell[1] + config[3*oIndex+1]*rcell[4] + config[3*oIndex+2]*rcell[7]
 *     scaleoposition[2] = config[3*oIndex]*rcell[2] + config[3*oIndex+1]*rcell[5] + config[3*oIndex+2]*rcell[8]
 */
  (__pyx_v_scaleoposition[0]) = ((((__pyx_v_config[(3 * __pyx_v_oIndex)]) * (__pyx_v_rcell[0])) + ((__pyx_v_config[((3 * __pyx_v_oIndex) + 1)]) * (__pyx_v_rcell[3]))) + ((__pyx_v_config[((3 * __pyx_v_oIndex) + 2)]) * (__pyx_v_rcell[6])));

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":58
 * 
 *     scaleoposition[0] = config[3*oIndex]*rcell[0] + config[3*oIndex+1]*rcell[3] + config[3*oIndex+2]*rcell[6]
 *     scaleoposition[1] = config[3*oIndex]*rcell[1] + config[3*oIndex+1]*rcell[4] + config[3*oIndex+2]*rcell[7]             # <<<<<<<<<<<<<<
 *     scaleoposition[2] = config[3*oIndex]*rcell[2] + config[3*oIndex+1]*rcell[5] + config[3*oIndex+2]*rcell[8]
 * 
 */
  (__pyx_v_scaleoposition[1]) = ((((__pyx_v_config[(3 * __pyx_v_oIndex)]) * (__pyx_v_rcell[1])) + ((__pyx_v_config[((3 * __pyx_v_oIndex) + 1)]) * (__pyx_v_rcell[4]))) + ((__pyx_v_config[((3 * __pyx_v_oIndex) + 2)]) * (__pyx_v_rcell[7])));

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":59
 *     scaleoposition[0] = config[3*oIndex]*rcell[0] + config[3*oIndex+1]*rcell[3] + config[3*oIndex+2]*rcell[6]
 *     scaleoposition[1] = config[3*oIndex]*rcell[1] + config[3*oIndex+1]*rcell[4] + config[3*oIndex+2]*rcell[7]
 *     scaleoposition[2] = config[3*oIndex]*rcell[2] + config[3*oIndex+1]*rcell[5] + config[3*oIndex+2]*rcell[8]             # <<<<<<<<<<<<<<
 * 
 *     for 0 <= i < indexes.dimensions[0]:
 */
  (__pyx_v_scaleoposition[2]) = ((((__pyx_v_config[(3 * __pyx_v_oIndex)]) * (__pyx_v_rcell[2])) + ((__pyx_v_config[((3 * __pyx_v_oIndex) + 1)]) * (__pyx_v_rcell[5]))) + ((__pyx_v_config[((3 * __pyx_v_oIndex) + 2)]) * (__pyx_v_rcell[8])));

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":61
 *     scaleoposition[2] = config[3*oIndex]*rcell[2] + config[3*oIndex+1]*rcell[5] + config[3*oIndex+2]*rcell[8]
 * 
 *     for 0 <= i < indexes.dimensions[0]:             # <<<<<<<<<<<<<<
 * 
 *         ind = 3*atomindex[i]
 */
  __pyx_t_4 = (__pyx_v_indexes->dimensions[0]);
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_t_4; __pyx_v_i++) {

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":63
 *     for 0 <= i < indexes.dimensions[0]:
 * 
 *         ind = 3*atomindex[i]             # <<<<<<<<<<<<<<
 * 
 *         x = config[ind]
 */
    __pyx_v_ind = (3 * (__pyx_v_atomindex[__pyx_v_i]));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":65
 *         ind = 3*atomindex[i]
 * 
 *         x = config[ind]             # <<<<<<<<<<<<<<
 *         y = config[ind+1]
 *         z = config[ind+2]
 */
    __pyx_v_x = (__pyx_v_config[__pyx_v_ind]);

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":66
 * 
 *         x = config[ind]
 *         y = config[ind+1]             # <<<<<<<<<<<<<<
 *         z = config[ind+2]
 * 
 */
    __pyx_v_y = (__pyx_v_config[(__pyx_v_ind + 1)]);

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":67
 *         x = config[ind]
 *         y = config[ind+1]
 *         z = config[ind+2]             # <<<<<<<<<<<<<<
 * 
 *         ind = 3*i
 */
    __pyx_v_z = (__pyx_v_config[(__pyx_v_ind + 2)]);

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":69
 *         z = config[ind+2]
 * 
 *         ind = 3*i             # <<<<<<<<<<<<<<
 * 
 *         scaleconfig[ind]   = x*rcell[0] + y*rcell[3] + z*rcell[6]
 */
    __pyx_v_ind = (3 * __pyx_v_i);

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":71
 *         ind = 3*i
 * 
 *         scaleconfig[ind]   = x*rcell[0] + y*rcell[3] + z*rcell[6]             # <<<<<<<<<<<<<<
 *         scaleconfig[ind+1] = x*rcell[1] + y*rcell[4] + z*rcell[7]
 *         scaleconfig[ind+2] = x*rcell[2] + y*rcell[5] + z*rcell[8]
 */
    (__pyx_v_scaleconfig[__pyx_v_ind]) = (((__pyx_v_x * (__pyx_v_rcell[0])) + (__pyx_v_y * (__pyx_v_rcell[3]))) + (__pyx_v_z * (__pyx_v_rcell[6])));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":72
 * 
 *         scaleconfig[ind]   = x*rcell[0] + y*rcell[3] + z*rcell[6]
 *         scaleconfig[ind+1] = x*rcell[1] + y*rcell[4] + z*rcell[7]             # <<<<<<<<<<<<<<
 *         scaleconfig[ind+2] = x*rcell[2] + y*rcell[5] + z*rcell[8]
 * 
 */
    (__pyx_v_scaleconfig[(__pyx_v_ind + 1)]) = (((__pyx_v_x * (__pyx_v_rcell[1])) + (__pyx_v_y * (__pyx_v_rcell[4]))) + (__pyx_v_z * (__pyx_v_rcell[7])));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":73
 *         scaleconfig[ind]   = x*rcell[0] + y*rcell[3] + z*rcell[6]
 *         scaleconfig[ind+1] = x*rcell[1] + y*rcell[4] + z*rcell[7]
 *         scaleconfig[ind+2] = x*rcell[2] + y*rcell[5] + z*rcell[8]             # <<<<<<<<<<<<<<
 * 
 *     s2 = 0.0
 */
    (__pyx_v_scaleconfig[(__pyx_v_ind + 2)]) = (((__pyx_v_x * (__pyx_v_rcell[2])) + (__pyx_v_y * (__pyx_v_rcell[5]))) + (__pyx_v_z * (__pyx_v_rcell[8])));
  }

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":75
 *         scaleconfig[ind+2] = x*rcell[2] + y*rcell[5] + z*rcell[8]
 * 
 *     s2 = 0.0             # <<<<<<<<<<<<<<
 *     for 0 <= i < indexes.dimensions[0]:
 * 
 */
  __pyx_v_s2 = 0.0;

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":76
 * 
 *     s2 = 0.0
 *     for 0 <= i < indexes.dimensions[0]:             # <<<<<<<<<<<<<<
 * 
 *         ind = 3*i
 */
  __pyx_t_4 = (__pyx_v_indexes->dimensions[0]);
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_t_4; __pyx_v_i++) {

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":78
 *     for 0 <= i < indexes.dimensions[0]:
 * 
 *         ind = 3*i             # <<<<<<<<<<<<<<
 * 
 *         sdx = scaleconfig[ind]   - scalehposition[0]
 */
    __pyx_v_ind = (3 * __pyx_v_i);

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":80
 *         ind = 3*i
 * 
 *         sdx = scaleconfig[ind]   - scalehposition[0]             # <<<<<<<<<<<<<<
 *         sdy = scaleconfig[ind+1] - scalehposition[1]
 *         sdz = scaleconfig[ind+2] - scalehposition[2]
 */
    __pyx_v_sdx = ((__pyx_v_scaleconfig[__pyx_v_ind]) - (__pyx_v_scalehposition[0]));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":81
 * 
 *         sdx = scaleconfig[ind]   - scalehposition[0]
 *         sdy = scaleconfig[ind+1] - scalehposition[1]             # <<<<<<<<<<<<<<
 *         sdz = scaleconfig[ind+2] - scalehposition[2]
 * 
 */
    __pyx_v_sdy = ((__pyx_v_scaleconfig[(__pyx_v_ind + 1)]) - (__pyx_v_scalehposition[1]));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":82
 *         sdx = scaleconfig[ind]   - scalehposition[0]
 *         sdy = scaleconfig[ind+1] - scalehposition[1]
 *         sdz = scaleconfig[ind+2] - scalehposition[2]             # <<<<<<<<<<<<<<
 * 
 *         sdx -= round(sdx)
 */
    __pyx_v_sdz = ((__pyx_v_scaleconfig[(__pyx_v_ind + 2)]) - (__pyx_v_scalehposition[2]));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":84
 *         sdz = scaleconfig[ind+2] - scalehposition[2]
 * 
 *         sdx -= round(sdx)             # <<<<<<<<<<<<<<
 *         sdy -= round(sdy)
 *         sdz -= round(sdz)
 */
    __pyx_v_sdx = (__pyx_v_sdx - __pyx_f_15order_parameter_round(__pyx_v_sdx));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":85
 * 
 *         sdx -= round(sdx)
 *         sdy -= round(sdy)             # <<<<<<<<<<<<<<
 *         sdz -= round(sdz)
 * 
 */
    __pyx_v_sdy = (__pyx_v_sdy - __pyx_f_15order_parameter_round(__pyx_v_sdy));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":86
 *         sdx -= round(sdx)
 *         sdy -= round(sdy)
 *         sdz -= round(sdz)             # <<<<<<<<<<<<<<
 * 
 *         rx = sdx*cell[0] + sdy*cell[3] + sdz*cell[6]
 */
    __pyx_v_sdz = (__pyx_v_sdz - __pyx_f_15order_parameter_round(__pyx_v_sdz));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":88
 *         sdz -= round(sdz)
 * 
 *         rx = sdx*cell[0] + sdy*cell[3] + sdz*cell[6]             # <<<<<<<<<<<<<<
 *         ry = sdx*cell[1] + sdy*cell[4] + sdz*cell[7]
 *         rz = sdx*cell[2] + sdy*cell[5] + sdz*cell[8]
 */
    __pyx_v_rx = (((__pyx_v_sdx * (__pyx_v_cell[0])) + (__pyx_v_sdy * (__pyx_v_cell[3]))) + (__pyx_v_sdz * (__pyx_v_cell[6])));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":89
 * 
 *         rx = sdx*cell[0] + sdy*cell[3] + sdz*cell[6]
 *         ry = sdx*cell[1] + sdy*cell[4] + sdz*cell[7]             # <<<<<<<<<<<<<<
 *         rz = sdx*cell[2] + sdy*cell[5] + sdz*cell[8]
 * 
 */
    __pyx_v_ry = (((__pyx_v_sdx * (__pyx_v_cell[1])) + (__pyx_v_sdy * (__pyx_v_cell[4]))) + (__pyx_v_sdz * (__pyx_v_cell[7])));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":90
 *         rx = sdx*cell[0] + sdy*cell[3] + sdz*cell[6]
 *         ry = sdx*cell[1] + sdy*cell[4] + sdz*cell[7]
 *         rz = sdx*cell[2] + sdy*cell[5] + sdz*cell[8]             # <<<<<<<<<<<<<<
 * 
 *         r = sqrt(rx*rx + ry*ry + rz*rz)
 */
    __pyx_v_rz = (((__pyx_v_sdx * (__pyx_v_cell[2])) + (__pyx_v_sdy * (__pyx_v_cell[5]))) + (__pyx_v_sdz * (__pyx_v_cell[8])));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":92
 *         rz = sdx*cell[2] + sdy*cell[5] + sdz*cell[8]
 * 
 *         r = sqrt(rx*rx + ry*ry + rz*rz)             # <<<<<<<<<<<<<<
 * 
 *         r /= conversionFactor
 */
    __pyx_v_r = sqrt((((__pyx_v_rx * __pyx_v_rx) + (__pyx_v_ry * __pyx_v_ry)) + (__pyx_v_rz * __pyx_v_rz)));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":94
 *         r = sqrt(rx*rx + ry*ry + rz*rz)
 * 
 *         r /= conversionFactor             # <<<<<<<<<<<<<<
 * 
 *         s2 += 0.8*exp(-r)
 */
    if (unlikely(__pyx_v_conversionFactor == 0)) {
      PyErr_Format(PyExc_ZeroDivisionError, "float division");
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    }
    __pyx_v_r = (__pyx_v_r / __pyx_v_conversionFactor);

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":96
 *         r /= conversionFactor
 * 
 *         s2 += 0.8*exp(-r)             # <<<<<<<<<<<<<<
 * 
 *         sdx = scaleconfig[ind]   - scaleoposition[0]
 */
    __pyx_v_s2 = (__pyx_v_s2 + (0.8 * exp((-__pyx_v_r))));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":98
 *         s2 += 0.8*exp(-r)
 * 
 *         sdx = scaleconfig[ind]   - scaleoposition[0]             # <<<<<<<<<<<<<<
 *         sdy = scaleconfig[ind+1] - scaleoposition[1]
 *         sdz = scaleconfig[ind+2] - scaleoposition[2]
 */
    __pyx_v_sdx = ((__pyx_v_scaleconfig[__pyx_v_ind]) - (__pyx_v_scaleoposition[0]));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":99
 * 
 *         sdx = scaleconfig[ind]   - scaleoposition[0]
 *         sdy = scaleconfig[ind+1] - scaleoposition[1]             # <<<<<<<<<<<<<<
 *         sdz = scaleconfig[ind+2] - scaleoposition[2]
 * 
 */
    __pyx_v_sdy = ((__pyx_v_scaleconfig[(__pyx_v_ind + 1)]) - (__pyx_v_scaleoposition[1]));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":100
 *         sdx = scaleconfig[ind]   - scaleoposition[0]
 *         sdy = scaleconfig[ind+1] - scaleoposition[1]
 *         sdz = scaleconfig[ind+2] - scaleoposition[2]             # <<<<<<<<<<<<<<
 * 
 *         sdx -= round(sdx)
 */
    __pyx_v_sdz = ((__pyx_v_scaleconfig[(__pyx_v_ind + 2)]) - (__pyx_v_scaleoposition[2]));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":102
 *         sdz = scaleconfig[ind+2] - scaleoposition[2]
 * 
 *         sdx -= round(sdx)             # <<<<<<<<<<<<<<
 *         sdy -= round(sdy)
 *         sdz -= round(sdz)
 */
    __pyx_v_sdx = (__pyx_v_sdx - __pyx_f_15order_parameter_round(__pyx_v_sdx));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":103
 * 
 *         sdx -= round(sdx)
 *         sdy -= round(sdy)             # <<<<<<<<<<<<<<
 *         sdz -= round(sdz)
 * 
 */
    __pyx_v_sdy = (__pyx_v_sdy - __pyx_f_15order_parameter_round(__pyx_v_sdy));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":104
 *         sdx -= round(sdx)
 *         sdy -= round(sdy)
 *         sdz -= round(sdz)             # <<<<<<<<<<<<<<
 * 
 *         rx = sdx*cell[0] + sdy*cell[3] + sdz*cell[6]
 */
    __pyx_v_sdz = (__pyx_v_sdz - __pyx_f_15order_parameter_round(__pyx_v_sdz));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":106
 *         sdz -= round(sdz)
 * 
 *         rx = sdx*cell[0] + sdy*cell[3] + sdz*cell[6]             # <<<<<<<<<<<<<<
 *         ry = sdx*cell[1] + sdy*cell[4] + sdz*cell[7]
 *         rz = sdx*cell[2] + sdy*cell[5] + sdz*cell[8]
 */
    __pyx_v_rx = (((__pyx_v_sdx * (__pyx_v_cell[0])) + (__pyx_v_sdy * (__pyx_v_cell[3]))) + (__pyx_v_sdz * (__pyx_v_cell[6])));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":107
 * 
 *         rx = sdx*cell[0] + sdy*cell[3] + sdz*cell[6]
 *         ry = sdx*cell[1] + sdy*cell[4] + sdz*cell[7]             # <<<<<<<<<<<<<<
 *         rz = sdx*cell[2] + sdy*cell[5] + sdz*cell[8]
 * 
 */
    __pyx_v_ry = (((__pyx_v_sdx * (__pyx_v_cell[1])) + (__pyx_v_sdy * (__pyx_v_cell[4]))) + (__pyx_v_sdz * (__pyx_v_cell[7])));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":108
 *         rx = sdx*cell[0] + sdy*cell[3] + sdz*cell[6]
 *         ry = sdx*cell[1] + sdy*cell[4] + sdz*cell[7]
 *         rz = sdx*cell[2] + sdy*cell[5] + sdz*cell[8]             # <<<<<<<<<<<<<<
 * 
 *         r = sqrt(rx*rx + ry*ry + rz*rz)
 */
    __pyx_v_rz = (((__pyx_v_sdx * (__pyx_v_cell[2])) + (__pyx_v_sdy * (__pyx_v_cell[5]))) + (__pyx_v_sdz * (__pyx_v_cell[8])));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":110
 *         rz = sdx*cell[2] + sdy*cell[5] + sdz*cell[8]
 * 
 *         r = sqrt(rx*rx + ry*ry + rz*rz)             # <<<<<<<<<<<<<<
 * 
 *         r /= conversionFactor
 */
    __pyx_v_r = sqrt((((__pyx_v_rx * __pyx_v_rx) + (__pyx_v_ry * __pyx_v_ry)) + (__pyx_v_rz * __pyx_v_rz)));

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":112
 *         r = sqrt(rx*rx + ry*ry + rz*rz)
 * 
 *         r /= conversionFactor             # <<<<<<<<<<<<<<
 * 
 *         s2 += 1.0*exp(-r)
 */
    if (unlikely(__pyx_v_conversionFactor == 0)) {
      PyErr_Format(PyExc_ZeroDivisionError, "float division");
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    }
    __pyx_v_r = (__pyx_v_r / __pyx_v_conversionFactor);

    /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":114
 *         r /= conversionFactor
 * 
 *         s2 += 1.0*exp(-r)             # <<<<<<<<<<<<<<
 * 
 *     s2 = tanh(2.656*s2) - 0.1
 */
    __pyx_v_s2 = (__pyx_v_s2 + (1.0 * exp((-__pyx_v_r))));
  }

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":116
 *         s2 += 1.0*exp(-r)
 * 
 *     s2 = tanh(2.656*s2) - 0.1             # <<<<<<<<<<<<<<
 * 
 *     return s2
 */
  __pyx_v_s2 = (tanh((2.656 * __pyx_v_s2)) - 0.1);

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":118
 *     s2 = tanh(2.656*s2) - 0.1
 * 
 *     return s2             # <<<<<<<<<<<<<<
 * 
 */
  __Pyx_XDECREF(__pyx_r);
  __pyx_t_5 = PyFloat_FromDouble(__pyx_v_s2); if (unlikely(!__pyx_t_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_5);
  __pyx_r = __pyx_t_5;
  __pyx_t_5 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_5);
  __Pyx_AddTraceback("order_parameter.order_parameter");
  __pyx_r = NULL;
  __pyx_L0:;
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

static PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    __Pyx_NAMESTR("order_parameter"),
    0, /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_s____main__, __pyx_k____main__, sizeof(__pyx_k____main__), 0, 0, 1, 1},
  {&__pyx_n_s____test__, __pyx_k____test__, sizeof(__pyx_k____test__), 0, 0, 1, 1},
  {&__pyx_n_s__configuration, __pyx_k__configuration, sizeof(__pyx_k__configuration), 0, 0, 1, 1},
  {&__pyx_n_s__conversionFactor, __pyx_k__conversionFactor, sizeof(__pyx_k__conversionFactor), 0, 0, 1, 1},
  {&__pyx_n_s__data, __pyx_k__data, sizeof(__pyx_k__data), 0, 0, 1, 1},
  {&__pyx_n_s__descr, __pyx_k__descr, sizeof(__pyx_k__descr), 0, 0, 1, 1},
  {&__pyx_n_s__dimensions, __pyx_k__dimensions, sizeof(__pyx_k__dimensions), 0, 0, 1, 1},
  {&__pyx_n_s__directCell, __pyx_k__directCell, sizeof(__pyx_k__directCell), 0, 0, 1, 1},
  {&__pyx_n_s__elsize, __pyx_k__elsize, sizeof(__pyx_k__elsize), 0, 0, 1, 1},
  {&__pyx_n_s__hIndex, __pyx_k__hIndex, sizeof(__pyx_k__hIndex), 0, 0, 1, 1},
  {&__pyx_n_s__indexes, __pyx_k__indexes, sizeof(__pyx_k__indexes), 0, 0, 1, 1},
  {&__pyx_n_s__nd, __pyx_k__nd, sizeof(__pyx_k__nd), 0, 0, 1, 1},
  {&__pyx_n_s__oIndex, __pyx_k__oIndex, sizeof(__pyx_k__oIndex), 0, 0, 1, 1},
  {&__pyx_n_s__order_parameter, __pyx_k__order_parameter, sizeof(__pyx_k__order_parameter), 0, 0, 1, 1},
  {&__pyx_n_s__reverseCell, __pyx_k__reverseCell, sizeof(__pyx_k__reverseCell), 0, 0, 1, 1},
  {&__pyx_n_s__scalec, __pyx_k__scalec, sizeof(__pyx_k__scalec), 0, 0, 1, 1},
  {&__pyx_n_s__scaleh, __pyx_k__scaleh, sizeof(__pyx_k__scaleh), 0, 0, 1, 1},
  {&__pyx_n_s__scaleo, __pyx_k__scaleo, sizeof(__pyx_k__scaleo), 0, 0, 1, 1},
  {&__pyx_n_s__type_num, __pyx_k__type_num, sizeof(__pyx_k__type_num), 0, 0, 1, 1},
  {0, 0, 0, 0, 0, 0, 0}
};
static int __Pyx_InitCachedBuiltins(void) {
  return 0;
}

static int __Pyx_InitCachedConstants(void) {
  __Pyx_RefNannySetupContext("__Pyx_InitCachedConstants");
  __Pyx_RefNannyFinishContext();
  return 0;
}

static int __Pyx_InitGlobals(void) {
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  return 0;
  __pyx_L1_error:;
  return -1;
}

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initorder_parameter(void); /*proto*/
PyMODINIT_FUNC initorder_parameter(void)
#else
PyMODINIT_FUNC PyInit_order_parameter(void); /*proto*/
PyMODINIT_FUNC PyInit_order_parameter(void)
#endif
{
  PyObject *__pyx_t_1 = NULL;
  #if CYTHON_REFNANNY
  void* __pyx_refnanny = NULL;
  __Pyx_RefNanny = __Pyx_RefNannyImportAPI("refnanny");
  if (!__Pyx_RefNanny) {
      PyErr_Clear();
      __Pyx_RefNanny = __Pyx_RefNannyImportAPI("Cython.Runtime.refnanny");
      if (!__Pyx_RefNanny)
          Py_FatalError("failed to import 'refnanny' module");
  }
  __pyx_refnanny = __Pyx_RefNanny->SetupContext("PyMODINIT_FUNC PyInit_order_parameter(void)", __LINE__, __FILE__);
  #endif
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_empty_bytes = PyBytes_FromStringAndSize("", 0); if (unlikely(!__pyx_empty_bytes)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  #ifdef __pyx_binding_PyCFunctionType_USED
  if (__pyx_binding_PyCFunctionType_init() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  #endif
  /*--- Library function declarations ---*/
  /*--- Threads initialization code ---*/
  #if defined(__PYX_FORCE_INIT_THREADS) && __PYX_FORCE_INIT_THREADS
  #ifdef WITH_THREAD /* Python build with threading support? */
  PyEval_InitThreads();
  #endif
  #endif
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4(__Pyx_NAMESTR("order_parameter"), __pyx_methods, 0, 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_NAMESTR(__Pyx_BUILTIN_MODULE_NAME));
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__Pyx_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  /*--- Initialize various global constants etc. ---*/
  if (unlikely(__Pyx_InitGlobals() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__pyx_module_is_main_order_parameter) {
    if (__Pyx_SetAttrString(__pyx_m, "__name__", __pyx_n_s____main__) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  }
  /*--- Builtin init code ---*/
  if (unlikely(__Pyx_InitCachedBuiltins() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Constants init code ---*/
  if (unlikely(__Pyx_InitCachedConstants() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  __pyx_ptype_15order_parameter_array_type = __Pyx_ImportType("Scientific.N", "array_type", sizeof(PyArrayObject), 0); if (unlikely(!__pyx_ptype_15order_parameter_array_type)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 26; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Type import code ---*/
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Include\nMOLDYN\numeric.pxi":36
 *     object PyArray_FromDims(int n_dimensions, int dimensions[], int item_type)
 * 
 * import_array()             # <<<<<<<<<<<<<<
 */
  import_array();

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":15
 *     return floor(r + 0.5) if (r > 0.0) else ceil(r - 0.5)
 * 
 * def order_parameter(array_type configuration, int hIndex, int oIndex, array_type directCell, array_type reverseCell,\             # <<<<<<<<<<<<<<
 *                     array_type indexes, array_type scalec, array_type scaleh, array_type scaleo, double conversionFactor):
 * 
 */
  __pyx_t_1 = PyCFunction_NewEx(&__pyx_mdef_15order_parameter_0order_parameter, NULL, __pyx_n_s__order_parameter); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_1);
  if (PyObject_SetAttr(__pyx_m, __pyx_n_s__order_parameter, __pyx_t_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;

  /* "C:\Datas\Eclipse_Projects\Python\nMOLDYN\trunk\Src\order_parameter.pyx":1
 * include 'python.pxi'             # <<<<<<<<<<<<<<
 * include 'numeric.pxi'
 * 
 */
  __pyx_t_1 = PyDict_New(); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(((PyObject *)__pyx_t_1));
  if (PyObject_SetAttr(__pyx_m, __pyx_n_s____test__, ((PyObject *)__pyx_t_1)) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(((PyObject *)__pyx_t_1)); __pyx_t_1 = 0;
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_1);
  if (__pyx_m) {
    __Pyx_AddTraceback("init order_parameter");
    Py_DECREF(__pyx_m); __pyx_m = 0;
  } else if (!PyErr_Occurred()) {
    PyErr_SetString(PyExc_ImportError, "init order_parameter");
  }
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
}

/* Runtime support code */

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name,
    PyObject* kw_name)
{
    PyErr_Format(PyExc_TypeError,
        #if PY_MAJOR_VERSION >= 3
        "%s() got multiple values for keyword argument '%U'", func_name, kw_name);
        #else
        "%s() got multiple values for keyword argument '%s'", func_name,
        PyString_AS_STRING(kw_name));
        #endif
}

static void __Pyx_RaiseArgtupleInvalid(
    const char* func_name,
    int exact,
    Py_ssize_t num_min,
    Py_ssize_t num_max,
    Py_ssize_t num_found)
{
    Py_ssize_t num_expected;
    const char *number, *more_or_less;

    if (num_found < num_min) {
        num_expected = num_min;
        more_or_less = "at least";
    } else {
        num_expected = num_max;
        more_or_less = "at most";
    }
    if (exact) {
        more_or_less = "exactly";
    }
    number = (num_expected == 1) ? "" : "s";
    PyErr_Format(PyExc_TypeError,
        #if PY_VERSION_HEX < 0x02050000
            "%s() takes %s %d positional argument%s (%d given)",
        #else
            "%s() takes %s %zd positional argument%s (%zd given)",
        #endif
        func_name, more_or_less, num_expected, number, num_found);
}

static int __Pyx_ParseOptionalKeywords(
    PyObject *kwds,
    PyObject **argnames[],
    PyObject *kwds2,
    PyObject *values[],
    Py_ssize_t num_pos_args,
    const char* function_name)
{
    PyObject *key = 0, *value = 0;
    Py_ssize_t pos = 0;
    PyObject*** name;
    PyObject*** first_kw_arg = argnames + num_pos_args;

    while (PyDict_Next(kwds, &pos, &key, &value)) {
        name = first_kw_arg;
        while (*name && (**name != key)) name++;
        if (*name) {
            values[name-argnames] = value;
        } else {
            #if PY_MAJOR_VERSION < 3
            if (unlikely(!PyString_CheckExact(key)) && unlikely(!PyString_Check(key))) {
            #else
            if (unlikely(!PyUnicode_CheckExact(key)) && unlikely(!PyUnicode_Check(key))) {
            #endif
                goto invalid_keyword_type;
            } else {
                for (name = first_kw_arg; *name; name++) {
                    #if PY_MAJOR_VERSION >= 3
                    if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                        PyUnicode_Compare(**name, key) == 0) break;
                    #else
                    if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                        _PyString_Eq(**name, key)) break;
                    #endif
                }
                if (*name) {
                    values[name-argnames] = value;
                } else {
                    /* unexpected keyword found */
                    for (name=argnames; name != first_kw_arg; name++) {
                        if (**name == key) goto arg_passed_twice;
                        #if PY_MAJOR_VERSION >= 3
                        if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                            PyUnicode_Compare(**name, key) == 0) goto arg_passed_twice;
                        #else
                        if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                            _PyString_Eq(**name, key)) goto arg_passed_twice;
                        #endif
                    }
                    if (kwds2) {
                        if (unlikely(PyDict_SetItem(kwds2, key, value))) goto bad;
                    } else {
                        goto invalid_keyword;
                    }
                }
            }
        }
    }
    return 0;
arg_passed_twice:
    __Pyx_RaiseDoubleKeywordsError(function_name, **name);
    goto bad;
invalid_keyword_type:
    PyErr_Format(PyExc_TypeError,
        "%s() keywords must be strings", function_name);
    goto bad;
invalid_keyword:
    PyErr_Format(PyExc_TypeError,
    #if PY_MAJOR_VERSION < 3
        "%s() got an unexpected keyword argument '%s'",
        function_name, PyString_AsString(key));
    #else
        "%s() got an unexpected keyword argument '%U'",
        function_name, key);
    #endif
bad:
    return -1;
}

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed,
    const char *name, int exact)
{
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (none_allowed && obj == Py_None) return 1;
    else if (exact) {
        if (Py_TYPE(obj) == type) return 1;
    }
    else {
        if (PyObject_TypeCheck(obj, type)) return 1;
    }
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, Py_TYPE(obj)->tp_name);
    return 0;
}

static CYTHON_INLINE unsigned char __Pyx_PyInt_AsUnsignedChar(PyObject* x) {
    const unsigned char neg_one = (unsigned char)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(unsigned char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned char)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to unsigned char" :
                    "value too large to convert to unsigned char");
            }
            return (unsigned char)-1;
        }
        return (unsigned char)val;
    }
    return (unsigned char)__Pyx_PyInt_AsUnsignedLong(x);
}

static CYTHON_INLINE unsigned short __Pyx_PyInt_AsUnsignedShort(PyObject* x) {
    const unsigned short neg_one = (unsigned short)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(unsigned short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned short)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to unsigned short" :
                    "value too large to convert to unsigned short");
            }
            return (unsigned short)-1;
        }
        return (unsigned short)val;
    }
    return (unsigned short)__Pyx_PyInt_AsUnsignedLong(x);
}

static CYTHON_INLINE unsigned int __Pyx_PyInt_AsUnsignedInt(PyObject* x) {
    const unsigned int neg_one = (unsigned int)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(unsigned int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned int)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to unsigned int" :
                    "value too large to convert to unsigned int");
            }
            return (unsigned int)-1;
        }
        return (unsigned int)val;
    }
    return (unsigned int)__Pyx_PyInt_AsUnsignedLong(x);
}

static CYTHON_INLINE char __Pyx_PyInt_AsChar(PyObject* x) {
    const char neg_one = (char)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(char)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to char" :
                    "value too large to convert to char");
            }
            return (char)-1;
        }
        return (char)val;
    }
    return (char)__Pyx_PyInt_AsLong(x);
}

static CYTHON_INLINE short __Pyx_PyInt_AsShort(PyObject* x) {
    const short neg_one = (short)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(short)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to short" :
                    "value too large to convert to short");
            }
            return (short)-1;
        }
        return (short)val;
    }
    return (short)__Pyx_PyInt_AsLong(x);
}

static CYTHON_INLINE int __Pyx_PyInt_AsInt(PyObject* x) {
    const int neg_one = (int)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(int)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to int" :
                    "value too large to convert to int");
            }
            return (int)-1;
        }
        return (int)val;
    }
    return (int)__Pyx_PyInt_AsLong(x);
}

static CYTHON_INLINE signed char __Pyx_PyInt_AsSignedChar(PyObject* x) {
    const signed char neg_one = (signed char)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(signed char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed char)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to signed char" :
                    "value too large to convert to signed char");
            }
            return (signed char)-1;
        }
        return (signed char)val;
    }
    return (signed char)__Pyx_PyInt_AsSignedLong(x);
}

static CYTHON_INLINE signed short __Pyx_PyInt_AsSignedShort(PyObject* x) {
    const signed short neg_one = (signed short)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(signed short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed short)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to signed short" :
                    "value too large to convert to signed short");
            }
            return (signed short)-1;
        }
        return (signed short)val;
    }
    return (signed short)__Pyx_PyInt_AsSignedLong(x);
}

static CYTHON_INLINE signed int __Pyx_PyInt_AsSignedInt(PyObject* x) {
    const signed int neg_one = (signed int)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(signed int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed int)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to signed int" :
                    "value too large to convert to signed int");
            }
            return (signed int)-1;
        }
        return (signed int)val;
    }
    return (signed int)__Pyx_PyInt_AsSignedLong(x);
}

static CYTHON_INLINE int __Pyx_PyInt_AsLongDouble(PyObject* x) {
    const int neg_one = (int)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(int)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to int" :
                    "value too large to convert to int");
            }
            return (int)-1;
        }
        return (int)val;
    }
    return (int)__Pyx_PyInt_AsLong(x);
}

static CYTHON_INLINE unsigned long __Pyx_PyInt_AsUnsignedLong(PyObject* x) {
    const unsigned long neg_one = (unsigned long)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned long");
            return (unsigned long)-1;
        }
        return (unsigned long)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned long");
                return (unsigned long)-1;
            }
            return PyLong_AsUnsignedLong(x);
        } else {
            return PyLong_AsLong(x);
        }
    } else {
        unsigned long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (unsigned long)-1;
        val = __Pyx_PyInt_AsUnsignedLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static CYTHON_INLINE unsigned PY_LONG_LONG __Pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    const unsigned PY_LONG_LONG neg_one = (unsigned PY_LONG_LONG)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned PY_LONG_LONG");
            return (unsigned PY_LONG_LONG)-1;
        }
        return (unsigned PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned PY_LONG_LONG");
                return (unsigned PY_LONG_LONG)-1;
            }
            return PyLong_AsUnsignedLongLong(x);
        } else {
            return PyLong_AsLongLong(x);
        }
    } else {
        unsigned PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (unsigned PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static CYTHON_INLINE long __Pyx_PyInt_AsLong(PyObject* x) {
    const long neg_one = (long)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to long");
            return (long)-1;
        }
        return (long)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to long");
                return (long)-1;
            }
            return PyLong_AsUnsignedLong(x);
        } else {
            return PyLong_AsLong(x);
        }
    } else {
        long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (long)-1;
        val = __Pyx_PyInt_AsLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static CYTHON_INLINE PY_LONG_LONG __Pyx_PyInt_AsLongLong(PyObject* x) {
    const PY_LONG_LONG neg_one = (PY_LONG_LONG)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to PY_LONG_LONG");
            return (PY_LONG_LONG)-1;
        }
        return (PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to PY_LONG_LONG");
                return (PY_LONG_LONG)-1;
            }
            return PyLong_AsUnsignedLongLong(x);
        } else {
            return PyLong_AsLongLong(x);
        }
    } else {
        PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static CYTHON_INLINE signed long __Pyx_PyInt_AsSignedLong(PyObject* x) {
    const signed long neg_one = (signed long)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to signed long");
            return (signed long)-1;
        }
        return (signed long)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to signed long");
                return (signed long)-1;
            }
            return PyLong_AsUnsignedLong(x);
        } else {
            return PyLong_AsLong(x);
        }
    } else {
        signed long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (signed long)-1;
        val = __Pyx_PyInt_AsSignedLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static CYTHON_INLINE signed PY_LONG_LONG __Pyx_PyInt_AsSignedLongLong(PyObject* x) {
    const signed PY_LONG_LONG neg_one = (signed PY_LONG_LONG)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to signed PY_LONG_LONG");
            return (signed PY_LONG_LONG)-1;
        }
        return (signed PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to signed PY_LONG_LONG");
                return (signed PY_LONG_LONG)-1;
            }
            return PyLong_AsUnsignedLongLong(x);
        } else {
            return PyLong_AsLongLong(x);
        }
    } else {
        signed PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (signed PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsSignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name,
    long size, int strict)
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    PyObject *py_name = 0;
    char warning[200];

    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(class_name);
    #else
    py_name = PyUnicode_FromString(class_name);
    #endif
    if (!py_name)
        goto bad;
    result = PyObject_GetAttr(py_module, py_name);
    Py_DECREF(py_name);
    py_name = 0;
    Py_DECREF(py_module);
    py_module = 0;
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError,
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (!strict && ((PyTypeObject *)result)->tp_basicsize > size) {
        PyOS_snprintf(warning, sizeof(warning),
            "%s.%s size changed, may indicate binary incompatibility",
            module_name, class_name);
        #if PY_VERSION_HEX < 0x02050000
        PyErr_Warn(NULL, warning);
        #else
        PyErr_WarnEx(NULL, warning, 0);
        #endif
    }
    else if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError,
            "%s.%s has the wrong size, try recompiling",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(py_module);
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(const char *name) {
    PyObject *py_name = 0;
    PyObject *py_module = 0;

    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(name);
    #else
    py_name = PyUnicode_FromString(name);
    #endif
    if (!py_name)
        goto bad;
    py_module = PyImport_Import(py_name);
    Py_DECREF(py_name);
    return py_module;
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        __pyx_empty_bytes, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        __pyx_empty_bytes  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_GET(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_unicode | t->is_str) {
            if (t->intern) {
                *t->p = PyUnicode_InternFromString(t->s);
            } else if (t->encoding) {
                *t->p = PyUnicode_Decode(t->s, t->n - 1, t->encoding, NULL);
            } else {
                *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
            }
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

/* Type Conversion Functions */

static CYTHON_INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   int is_true = x == Py_True;
   if (is_true | (x == Py_False) | (x == Py_None)) return is_true;
   else return PyObject_IsTrue(x);
}

static CYTHON_INLINE PyObject* __Pyx_PyNumber_Int(PyObject* x) {
  PyNumberMethods *m;
  const char *name = NULL;
  PyObject *res = NULL;
#if PY_VERSION_HEX < 0x03000000
  if (PyInt_Check(x) || PyLong_Check(x))
#else
  if (PyLong_Check(x))
#endif
    return Py_INCREF(x), x;
  m = Py_TYPE(x)->tp_as_number;
#if PY_VERSION_HEX < 0x03000000
  if (m && m->nb_int) {
    name = "int";
    res = PyNumber_Int(x);
  }
  else if (m && m->nb_long) {
    name = "long";
    res = PyNumber_Long(x);
  }
#else
  if (m && m->nb_int) {
    name = "int";
    res = PyNumber_Long(x);
  }
#endif
  if (res) {
#if PY_VERSION_HEX < 0x03000000
    if (!PyInt_Check(res) && !PyLong_Check(res)) {
#else
    if (!PyLong_Check(res)) {
#endif
      PyErr_Format(PyExc_TypeError,
                   "__%s__ returned non-%s (type %.200s)",
                   name, name, Py_TYPE(res)->tp_name);
      Py_DECREF(res);
      return NULL;
    }
  }
  else if (!PyErr_Occurred()) {
    PyErr_SetString(PyExc_TypeError,
                    "an integer is required");
  }
  return res;
}

static CYTHON_INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static CYTHON_INLINE PyObject * __Pyx_PyInt_FromSize_t(size_t ival) {
#if PY_VERSION_HEX < 0x02050000
   if (ival <= LONG_MAX)
       return PyInt_FromLong((long)ival);
   else {
       unsigned char *bytes = (unsigned char *) &ival;
       int one = 1; int little = (int)*(unsigned char*)&one;
       return _PyLong_FromByteArray(bytes, sizeof(size_t), little, 0);
   }
#else
   return PyInt_FromSize_t(ival);
#endif
}

static CYTHON_INLINE size_t __Pyx_PyInt_AsSize_t(PyObject* x) {
   unsigned PY_LONG_LONG val = __Pyx_PyInt_AsUnsignedLongLong(x);
   if (unlikely(val == (unsigned PY_LONG_LONG)-1 && PyErr_Occurred())) {
       return (size_t)-1;
   } else if (unlikely(val != (unsigned PY_LONG_LONG)(size_t)val)) {
       PyErr_SetString(PyExc_OverflowError,
                       "value too large to convert to size_t");
       return (size_t)-1;
   }
   return (size_t)val;
}


#endif /* Py_PYTHON_H */
